backend:
  name: github
  repo: stableotto/hotelbarstools
  branch: main

# Uncomment for local development only
# local_backend: true

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "collections"
    label: "Collections"
    folder: "src/content/collections"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Hero Image", name: "hero_image", widget: "image"}
      - {label: "Hero Alt Text", name: "hero_alt", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Order", name: "order", widget: "number", default: 0}
      - label: "Features"
        name: "features"
        widget: "list"
        field: {label: "Feature", name: "feature", widget: "string"}
      - label: "Specifications"
        name: "specifications"
        widget: "object"
        fields:
          - label: "Materials"
            name: "materials"
            widget: "list"
            field: {label: "Material", name: "material", widget: "string"}
          - {label: "Dimensions", name: "dimensions", widget: "string"}
          - {label: "Weight", name: "weight", widget: "string"}
          - {label: "Warranty", name: "warranty", widget: "string"}
      - label: "Products"
        name: "products"
        widget: "list"
        fields:
          - {label: "ID", name: "id", widget: "string"}
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}
          - {label: "Price Range", name: "price_range", widget: "string"}
          - {label: "Material", name: "material", widget: "string"}
          - label: "Colors"
            name: "colors"
            widget: "list"
            field: {label: "Color", name: "color", widget: "string"}
          - {label: "Dimensions", name: "dimensions", widget: "string"}
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Keywords"
            name: "keywords"
            widget: "list"
            field: {label: "Keyword", name: "keyword", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/content/pages/home.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Hero Background", name: "heroBackground", widget: "image"}
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Subtitle", name: "heroSubtitle", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Settings"
        name: "site"
        file: "src/content/settings/site.json"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}
          - {label: "Social Links", name: "social", widget: "object", fields: [
              {label: "Facebook", name: "facebook", widget: "string", required: false},
              {label: "Instagram", name: "instagram", widget: "string", required: false},
              {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
            ]}
      
      - label: "Navigation"
        name: "navigation"
        file: "src/content/settings/navigation.json"
        fields:
          - {label: "Main Navigation", name: "main", widget: "list", fields: [
              {label: "Label", name: "label", widget: "string"},
              {label: "URL", name: "url", widget: "string"}
            ]}
          - {label: "Footer Navigation", name: "footer", widget: "list", fields: [
              {label: "Label", name: "label", widget: "string"},
              {label: "URL", name: "url", widget: "string"}
            ]}

  - name: "clientele"
    label: "Clientele"
    folder: "src/content/clientele"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Company Name", name: "name", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Order", name: "order", widget: "number", default: 0}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Content", name: "body", widget: "markdown"} 